apiVersion: v1
kind: ServiceAccount
metadata:
  name: aasserver
---
apiVersion: v1
kind: Service
metadata:
  name: aasserver
  labels:
    app: aasserver
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    app: aasserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aasserver
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aasserver
  template:
    metadata:
      labels:
        app: aasserver
        version: v1
    spec:
      containers:
      - name: aasserver
        image: timfa/aasserver:latest
        env:
        - name: "adtServiceUrl"
          value: "<ADT URL>"
        - name: "adtClientId"
          value: "<adtClientId>"
        - name: "adtClientSecret"
          value: "<adtClientSecret>"
        - name: "adtTenantId"
          value: "<adtTenantId>"
        - name: "PFX_CERT_PATH"
          value: "uudex.pfx"
        - name: "PFX_CERT_PASS"
          value: "flexchess1234"
        - name: "UUDEX_USER"
          value: "uudex-user"
        - name: "UUDEX_PASS"
          value: "umbrella2021"
        resources:
          requests:
            cpu: 10m
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      nodeSelector:
         kubernetes.io/arch: amd64
         
